name: Send Blog Update Email

on:
  push:
    paths:
      - 'docs/MAIL.md'

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract blog post title
        id: extract_title
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "BLOG_POST_TITLE=$(echo "$COMMIT_MESSAGE" | grep -oP '(?<=Title: ).*')" >> $GITHUB_ENV

      - name: Read email list
        id: read_email_list
        run: echo "emails=$(cat email_list.txt)" >> $GITHUB_ENV

      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Ed's Blog Update: ${{ env.BLOG_POST_TITLE }}"
          to: ${{ env.emails }}
          from: "Edwin Zhan <edwinzhanblog@gmail.com>"
          body: Your plain text content here
          html_body: file://docs/MAIL.md
          convert_markdown: true