name: Send Blog Update Email

on:
  workflow_dispatch:
    inputs:
      blog_post_title:
        description: 'Title of the updated blog post'
        required: true

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check HTML file existence
        run: |
          ls -l
      - name: Read email list
        id: read_email_list
        run: echo "emails=$(cat email_list.txt)" >> $GITHUB_ENV
      - name: Send mail
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Ed's Blog Update: ${{ github.event.inputs.blog_post_title }}"
          to: ${{ env.emails }}
          from: "Edwin Zhan <edwinzhanblog@gmail.com>" # Name + email
          body: Your plain text content here
          html_body: file://MAIL.md
          convert_markdown: true



